### ISSUE TITLE
Face rendering seems a bit off?

### ISSUE THREAD

**Issue by justinclift** [bobcob7/wasm-stl-viewer#1]
This looks like a useful project. :smile:

Trying it with a few random STLs from Thingiverse, at the moment it seems like solid/face rendering isn't working quite right.  For example, using the "Apex_Legends_Supply_Box_Bottom" STL file from [here](https://www.thingiverse.com/thing:3569648), shows this:

![wasm_stl_viewer1](https://user-images.githubusercontent.com/406299/60593324-d77ee500-9de5-11e9-9f2a-ac7b613970f5.png)

That being said, it's possible the STL files themselves aren't quite right and the various programs used to load them know how to work around common problems. :wink:

**Comment by bobcob7** [comment]
After looking at the model and trying several others, I'm finding that the model breaks up after ~65535. I guess it's time to upgrade to 32-bit integers

**Comment by justinclift** [comment]
Ahhh.  Yeah, makes sense. :smile:
