### ISSUE TITLE
TinyGo Support

### ISSUE THREAD

**Issue by bobcob7** [bobcob7/wasm-stl-viewer#4]
TinyGo allows for smaller binary sizes, however also comes with a lot of limitations.
The STL library will probably need to be forked or reimplemented in this library to remove it's concurrent loading features.

**Comment by justinclift** [comment]
Doing an initial port here: https://github.com/justinclift/wasm-stl-viewer

Also, an initial port of the STL library too: https://github.com/justinclift/stl

That STL library port is triggering some bugs in TinyGo though ([#696](https://github.com/tinygo-org/tinygo/issues/696), [#699](https://github.com/tinygo-org/tinygo/issues/699)), so I'm having to figure out some workarounds. :frowning:

**Comment by justinclift** [comment]
Both of those TinyGo bugs look to be fixed, so going to see if this will work. :smile:
